version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "6000:27017"
    volumes:
      - mongo_data:/data/db

  mongo-seed:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./server/animals_mongo_backup:/backup
    entrypoint: ["sh", "-c", "sleep 5 && mongorestore --host mongo --db animals_db /backup/animals_db"]
    restart: "no"

  server:
    image: freeahea/animal_adoption_server:latest
    container_name: server
    depends_on:
      - mongo
      - mongo-seed
    environment:
      - MONGO_URL=mongodb://mongo:27017/animals_db
    ports:
      - "5000:5000"

  client:
    image: freeahea/animal_adoption_client:latest
    container_name: client
    ports:
      - "4200:80"
    depends_on:
      - server

volumes:
  mongo_data:
