global:
  scrape_interval: 5s

scrape_configs:
# Only server metrics
  - job_name: 'server-metrics'
    static_configs:
      - targets: ['server:5000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

