global:
  scrape_interval: 5s

scrape_configs:
# Only server metrics
  - job_name: 'server-metrics'
    static_configs:
      - targets: ['server:5000']

  - job_name: 'nginx'
    metrics_path: /nginx_status
    static_configs:
      - targets: ['client:80']
